encyclopedia/urls.py
from django.urls import path

from . import views
app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("edit/<str:title>", views.edit, name="edit"),
    path("create", views.create, name="create"),
    path("search",views.search, name="search"),
    path("randoms", views.randoms, name="randoms"),
    path("<str:title>", views.entry, name="entry")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
import markdown
from . import util
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect
import random

class NewSearchForm(forms.Form):
    query = forms.CharField(label='', widget=forms.TextInput(attrs={"class":"search","placeholder":"Search Encyclopedia","autocomplete":"off"}))

#TODO
class EditForm(forms.Form):
    title = forms.CharField(label="Edit Title")
    body = forms.CharField(label="Edit Body", widget=forms.Textarea(
        attrs={'rows': 1, 'cols': 10}))

#TODO
class CreateNewForm(forms.Form):
    title = forms.CharField(label='Add Title',widget = forms.TextInput(attrs={'autocomplete':'off'})) 
    body =  forms.CharField(label='', widget = forms.Textarea(attrs={'row':1,'cols':10}))

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form": NewSearchForm()
    })

def entry(request, title):
    if util.get_entry(title) == None:
        return render(request,"encyclopedia/error.html",{
            "form": NewSearchForm()
        })
    else:
        html_content = markdown.markdown(util.get_entry(title))
        return render(request,"encyclopedia/entry.html", {
            "title": title,
            "html": html_content,
            "form": NewSearchForm()
        })

def search(request):
    if request.method == "POST":
        present = False
        form  = NewSearchForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data.get("query")
            for entry in util.list_entries():
                if data == entry:
                    html_content = markdown.markdown(util.get_entry(data))
                    present = True
                    break
            if present:
                return render(request,"encyclopedia/entry.html", {
                    "title": data,
                    "html": html_content,
                    "form": form
                    })
            else:
                l = []
                for entry in util.list_entries():
                    if data in entry:
                        l.append(entry)
                if len(l) == 0:
                    return render(request,"encyclopedia/error.html",{
                    "form": NewSearchForm()
                    })
                else:
                    return render(request,"encyclopedia/index.html", {
                        "entries": l,
                        "form": form
                    })
    else:
        return render(request,"encyclopedia/error.html",{
            "form": NewSearchForm()
        })        

def create(request):
    if request.method == "POST":
        cform = CreateNewForm(request.POST)
        if cform.is_valid():
            title = cform.cleaned_data["title"]
            body = cform.cleaned_data["body"]
            present = False
            for entry in util.list_entries():
                if title == entry:
                    present = True
                    break
            if present:
                return render(request,"encyclopedia/create_error.html",{
                    "form":NewSearchForm()
                })
            else:
                util.save_entry(title,body)
                html_content = markdown.markdown(util.get_entry(title))
                return render(request,"encyclopedia/entry.html",{
                    "title": title,
                    "html": html_content,
                    "form": NewSearchForm()
                }) 
                
    else:
        return render(request,"encyclopedia/create.html", {
            "form":NewSearchForm(),
            "cform":CreateNewForm()
        })

def edit(request, title):
    if request.method == "POST":
        editform = EditForm(request.POST)
        if editform.is_valid():
            title = editform.cleaned_data.get("title")
            body = editform.cleaned_data.get("body")
            # saving the new content
            util.save_entry(title, body)
            html_content = markdown.markdown(util.get_entry(title))
            return render(request,"encyclopedia/entry.html",{
                "title": title,
                "html": html_content,
                "form": NewSearchForm()
            })
    else:
        editform = EditForm({"title": title, "body": util.get_entry(title)})
        return render(request, "encyclopedia/edit.html", {"form": NewSearchForm(), "editform": editform})
 
def randoms(request):
    entries = util.list_entries()
    num = len(entries)
    # generating a random number for the entry
    entry = random.randint(0, num-1)
    title = entries[entry]
    html_content = markdown.markdown(util.get_entry(title))
    return render(request,"encyclopedia/randoms.html",{
        "form": NewSearchForm(),
        "title": title,
        "content": html_content
    })

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create 
{% endblock %}

{% block body %}

<form action="{% url 'encyclopedia:create' %}" method="POST">
    {% csrf_token %}
    {{ cform }}
    <input type="submit" value="Save" name="submit">
</form>
    
{% endblock %}

encyclopedia/templates/encyclopedia/create_error.html
{% extends "encyclopedia/layout.html" %}
{% block body %}
    <h2> Your created Page already exists! </h2>
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit
{% endblock %}

{% block body %}

    <div>
        <form action="{% url 'encyclopedia:edit' title=editform.data.title %}" method="POST">
            {% csrf_token %}
            {{editform}}
            <input type="Submit" name="submit" value="Submit"/>
        </form>
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock%}

{% block body %}

        {{ html|safe }}
        <a href="{% url 'encyclopedia:edit' title %}">EDIT</a>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block body%}

    <h1>Your Requested Page was not found.</h1>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li> <a href="/wiki/{{entry}}" > {{ entry }} </a> </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randoms' %}"> Random Page </a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/randoms.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}

    <div class="container">
        {{ content | safe }}
    </div>
    <a href="edit/{{title}}"> EDIT </a>
    
{% endblock %}